name = "square-fog-ec53"
compatibility_date = "2024-07-30"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTFkZDIwMTUtNzk2MS00NzNiLWE4YjctMGMzMzBiN2JmMGYwIiwidGVuYW50X2lkIjoiZTExZDg0OWIyMmQxYjE5N2NlZGU3MTA5NjY4YTM5NjU5Njc5MjgxZjFlNGVmZWFlYWNmOGJlNjU2ZWRjYzBlMSIsImludGVybmFsX3NlY3JldCI6ImE0YzBlNDFhLWIxOWUtNGJjNS1hY2Y5LTUyMmVkZTgwYzQwNCJ9.0GJrRHiyiMQ4BB9SHwkiIc1XShso-WIz3_NOvRbQ-PU"

JWT_SECRET="ninjadojoshifuyoshimarioluigipeachbowser"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"